#
# To deploy:
#
# kubectl apply -f scripts/deploy.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service
          #image: tohodson/ratingcurve-service:latest
          image: tohodson/ratingcurve-service:main
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "4000"
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            httpGet:
              path: /healthz
              port: 4000
              scheme: HTTP
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: rating-service
spec:
  selector:
    app: rating-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
