version: '3'
services:

  ratingcurve:
    image: ratingcurve-service
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ratingcurve-service
    ports:
     - "4000:80"
    environment:
      - PORT=80
    restart: "no"
