version: '3'
services:

  ratingcurve:
    image: rating-service
    build: 
      context: ./rating-service
      dockerfile: Dockerfile
      args:
      - FLASK_RUN_PORT=80
    container_name: rating-service
    ports:
     - "4000:80"
    restart: "no"
