apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
spec:
  replicas: 1
  selector:
  matchLabels:
    app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service
          image: tohodson/ratingcurve-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "4000"
